export { default as Navbar } from './navbar'
export { default as BackgroundImage } from './backgroundImage'
export {default as Features} from './features'
export { default as About } from './about'
export { default as Footer } from './footer'
export {default as ContactForm} from './contactForm'