import Head from 'next/head'
import { Navbar, BackgroundImage, About, Footer, Testimonials, Gallery } from '../components'


export default function Home() {
	return (
		<>
			<Head>
				<title>Dyka Design</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Navbar />
			{/* // TODO ADD INTERNAL IMAGE INSTEAD OF DOWNLOADED */}
      <BackgroundImage image='https://mir-s3-cdn-cf.behance.net/project_modules/fs/6f4b1a113393045.6026a9d2a3d7c.jpg' backgroundPosition={'center center'} text='test' />
			<About />
			<Testimonials />
			<Gallery/>
      <Footer/>
		</>
	)
}
