import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Navbar, BackgroundImage, About, Footer } from '../components'
import image from '../public/assets/heroimage.webp'

export default function Home() {
	return (
		<>
			<Head>
				<title>Dyka Design</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Navbar />
      <BackgroundImage image='https://mir-s3-cdn-cf.behance.net/project_modules/fs/6f4b1a113393045.6026a9d2a3d7c.jpg' backgroundPosition={'center center'} text='test' />
      <About />
      <Footer/>
		</>
	)
}
